/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author UNKNOWN'PC
 */
public class PilihGambarButtonFullScreen extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PilihGambarButtonFullScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel = new javax.swing.JPanel();
        rusaLB = new javax.swing.JLabel();
        kudanilLB = new javax.swing.JLabel();
        kudaLB = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        rusaBT = new javax.swing.JButton();
        kudanilBT = new javax.swing.JButton();
        kudaBT = new javax.swing.JButton();
        exitBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Penampil Gambar Button FullScreen");

        imagePanel.setAlignmentX(1.0F);
        imagePanel.setAlignmentY(1.0F);
        imagePanel.setLayout(new java.awt.CardLayout());

        rusaLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rusaLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/rusa.jpg"))); // NOI18N
        rusaLB.setToolTipText("null");
        rusaLB.setMinimumSize(new java.awt.Dimension(316, 400));
        rusaLB.setName("null"); // NOI18N
        rusaLB.setPreferredSize(new java.awt.Dimension(316, 400));
        rusaLB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        imagePanel.add(rusaLB, "0");
        rusaLB.getAccessibleContext().setAccessibleName("0");

        kudanilLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kudanilLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/kudanil.jpg"))); // NOI18N
        kudanilLB.setMaximumSize(new java.awt.Dimension(316, 400));
        kudanilLB.setMinimumSize(new java.awt.Dimension(316, 400));
        kudanilLB.setName("null"); // NOI18N
        kudanilLB.setPreferredSize(new java.awt.Dimension(316, 400));
        imagePanel.add(kudanilLB, "1");
        kudanilLB.getAccessibleContext().setAccessibleName("1");

        kudaLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kudaLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/kuda.jpg"))); // NOI18N
        kudaLB.setToolTipText("null");
        kudaLB.setName("null"); // NOI18N
        imagePanel.add(kudaLB, "2");
        kudaLB.getAccessibleContext().setAccessibleName("2");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        rusaBT.setText("Rusa");
        rusaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rusaBTActionPerformed(evt);
            }
        });
        buttonPanel.add(rusaBT);

        kudanilBT.setText("Kudanil");
        kudanilBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kudanilBTActionPerformed(evt);
            }
        });
        buttonPanel.add(kudanilBT);

        kudaBT.setText("Kuda");
        kudaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kudaBTActionPerformed(evt);
            }
        });
        buttonPanel.add(kudaBT);

        exitBT.setText("Exit");
        exitBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTActionPerformed(evt);
            }
        });
        buttonPanel.add(exitBT);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rusaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rusaBTActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, "0");
    }//GEN-LAST:event_rusaBTActionPerformed

    private void kudanilBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kudanilBTActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, "1");
    }//GEN-LAST:event_kudanilBTActionPerformed

    private void kudaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kudaBTActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, "2");
    }//GEN-LAST:event_kudaBTActionPerformed

    private void exitBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PilihGambarButtonFullScreen FullFrame = new PilihGambarButtonFullScreen();
            
                GraphicsDevice device =
                        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                device.setFullScreenWindow(FullFrame);
                
                FullFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton exitBT;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JButton kudaBT;
    private javax.swing.JLabel kudaLB;
    private javax.swing.JButton kudanilBT;
    private javax.swing.JLabel kudanilLB;
    private javax.swing.JButton rusaBT;
    private javax.swing.JLabel rusaLB;
    // End of variables declaration//GEN-END:variables
}
